name: Build & Deploy to Cloud Run

on:
  push:
    branches: [main]  # Deploy when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for Workload Identity Federation

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      REGION: ${{ secrets.GCP_REGION }}
      SERVICE: ${{ secrets.GCP_SERVICE }}
      REPO: ${{ secrets.GCP_REPO }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # 1. Check out code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: gha-cloud-run@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      # 3. Build & push container with Cloud Build
      - name: Build and Push Container
        id: build
        uses: google-github-actions/build@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/backend:${{ env.IMAGE_TAG }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/backend:latest
          timeout: 1800

      # 4. Deploy to Cloud Run
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: ${{ steps.build.outputs.image }}
          region: ${{ env.REGION }}
          allow_unauthenticated: true

      # 5. Health check
      - name: Health Check
        run: |
          echo "Deployment completed!"
          echo "Service URL: ${{ steps.deploy.outputs.url }}"
          curl --fail -s "${{ steps.deploy.outputs.url }}/health" && echo "✅ Health check passed!" 